models:
  yolo:
    checkpoint: yolov8m.pt
    version: "8.3.2"
  
  sam2:
    checkpoint: sam2_hiera_large.pt
    version: "2.0"
  
  insightface:
    det_model: buffalo_l
    rec_model: buffalo_l
    version: "0.7.3"
  
  emonet:
    checkpoint: emonet_8.pth
    version: "1.0"
  
  paddleocr:
    det_model: ch_PP-OCRv4_det
    rec_model: ch_PP-OCRv4_rec
    version: "2.7"
  
  deepfont:
    checkpoint: deepfont_classifier.pth
    version: "1.0"
  
  realesrgan:
    model: RealESRGAN_x4plus
    version: "0.3.0"
  
  qwen:
    model: Qwen/Qwen2.5-VL-7B-Instruct
    quantization: awq
    max_model_len: 8192
  
  yamnet:
    checkpoint: yamnet.h5
    version: "1.0"
  
  pyannote:
    pipeline: pyannote/speaker-diarization-3.1
    version: "3.1"
  
  beatnet:
    version: "1.0"
  
  whisper:
    model: base
    version: "1.0"
